export interface IProduct {
  id: string,
  title: string,
  brand_name: string,
  description: string,
  image: string,
  upload_image: string,
  avg_rating: null | number,
  total_reviews: number,
  sell_price: string,
  discount_price: string,
  clicks: number,
  website_from: string,
  category_id: string,
  reviews: string[],
}